{{- if .Values.rbac.create }}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ template "prometheus-cloudwatch-exporter.fullname" . }}
  labels:
    app: {{ template "prometheus-cloudwatch-exporter.name" . }}
    chart: {{ template "prometheus-cloudwatch-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups: [""]
    resources: ["secrets","configmap"]
    resourceNames: ["{{ template "prometheus-cloudwatch-exporter.fullname" . }}"]
    verbs: ["get"]
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: annotate-sa
  namespace: monitoring
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts","pods"]
    verbs: ["get","list","patch",'delete"]
